version: "2"

services:
  softether:
    container_name: softether
    image: siomiz/softethervpn
    restart: always
    volumes:
      - softether_data:/usr/vpnserver
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 1194:1194/udp
      - 5555:5555/tcp

volumes:
  softether_data:
    driver: local-persist
    driver_opts:
      mountpoint: /docker-data/softether
